---
title: "binomial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

```{r}
install.packages("devtools")
install.packages("roxygen2")

devtools::create("binomial")
```

## 1.1
```{r}
# private auxiliary function to test if an input prob is a valid probability value.
check_prob <- function(prob){
  if (prob<0 | prob>1){
    stop("invalid prob value")
  }
  return(TRUE)
}
```

```{r}
# private auxiliary function to test if an input trials is a valid value for number of trials.
check_trials <- function(trials){
  if (trials<0 | trials%%1!=0){
    stop("invalid trials value")
  }
  return(TRUE)
}
```

```{r}
# private auxiliary function to test if an input success is a valid value for number of successes.
check_success <- function(success, trials){
  if (success>=0 & length(success)<=length(trials)){
    return(TRUE)
  }else if (length(success)>length(trials)){
    stop("success cannot be greater than trials")
  }else{
    stop("invalid success value")
  }
}


```
## 1.2
```{r}
aux_mean <- function(trials, prob) {
  return(trials*prob)
}

aux_variance <- function(trials, prob) {
  return((trials*prob*(1-prob))**0.5)
}

aux_mode <- function(trials, prob) {
  m = integer(trials*prob + prob)
  if ((trials*prob + prob)%%1==0){
    return(m, m-1)
  }else{
    return(m)
  }
}

aux_skewness <- function(trials, prob) {
  return((1-2*prob)/(trials*prob*(1-prob))**0.5)
}

aux_kurtosis <- function(trials, prob) {
  return((1-6*prob*(1-prob))/(trials*prob*(1-prob)))
}
```
## 1.3
```{r}
#' @tital bin_choose
#' @description function that calculates the number of combinations in which k successes can occur in n trials 
#' @param n number of trails
#' @param k number of successes
#' @return computed result
bin_choose <- function(n,k){
  if (k>n) {
    stop("k cannot be greater than n")
  }else{
    return(factorial(n)/(factorial(k)*factorial(n-k)))
  }
}
```
## 1.4
```{r}
#' @tital bin_probability
#' @description function that calculates the the probability of getting the exact number of success in a number of trails. 
#' @param n number of trails
#' @param k number of successes
#' @param p probability of success
#' @return computed result
bin_probability <- function(n,k,p){
  if (check_trials(n)!=TRUE) {
    stop("invalid trails value")
  }else if (check_prob(p)!=TRUE){
    stop("invalid probability value")
  }else if (check_success(k, n)!=TRUE){
    stop("invalid success value")
  }else{
    return(bin_choose(n,k)*(p**k)*(1-p)**(n-k))
  }
}

```

